project:
  type: website
  output-dir: docs
website:
  title: "Datafigure"
  favicon: "fav.png"
  search: false
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Koolitused
      - href: consulting.qmd
        text: Konsult
      - href: past.qmd
        text: Tööd ja kajastus
      - href: contact.qmd
        text: Kontakt
      - href: english.qmd
        text: In English
format:
  html:
    theme: simplex
    css: styles.css


