---
title: "Past workshops"
---

This is a running list of all past workshops.

**2023**

- Spring 2023: multiple AI-related workshops at Estonian companies, universities, schools, and the Ministry of Culture.

- "Generative AI: ChatGPT, Stable Diffusion and other machines that generate text, images and content". Workshops at Tallinn University / Baltic Film, Media and Arts School. 20 March 2023.
- Several Generative AI, ChatGPT and Stable Diffusion workshops for private companies, March 2023.
- "ChatGPT and the new text generators. What are they, and how to proceed in a world where AI can do your exams and homework?" 3 workshops at Tallinn University, February 2023.


**2022**

- Invited workshop on dataviz in the "Data science and digital humanities" course at Tartu University.
- Basics of R for data visualization and working with large multilingual datasets - 2 workshops at the Baltic Summer School of Digital Humanities 2022, Riga, Latvia, 26-27 July Setup instructions and materials [here](https://andreskarjus.github.io/artofthefigure/riga2022/)
- Summer School of Linguistics 2022, August, České Budějovice, Czech Republic.

**2021**

- Hacking Digital Heritage, workshop and hackathon, part of the "Digital Data in Service of Cultural Heritage" [conference](https://meremuuseum.ee/workshop2021/), 25 November 2021. 
- Exploring and visualizing your data using R, a full-day workshop at the Baltic Summer School of Digital Humanities 2021: Digital Methods in Humanities and Social Sciences (August 2021).
- ~~Tartu Summer School of Semiotics~~ August 2021; invited, but event corona-cancelled
- Dataviz and text analytics lecture and workshop in the Cultural Data Analytics I course at Tallinn University (April 2021, 2022).

(Datafigure Ltd was founded in 2021; the workshops listed below were organized by Andres as a private instructor)

**2020**

- Two guest workshops on dataviz in the "Data science and digital humanities" (Andmeteadus ja digihumanitaaria) fall semester 2020 course at Tartu University.
- Visualising Your Data Using R. Workshop at the Digital Methods in Humanities and Social Sciences Summer School, August 24-27, 2020, University of Tartu.
-  Visualising Your Data Using R. Online summer session workshop for the University of Edinburgh PPLS Writing Centre. 
- ~~The Summer School of Linguistics~~ Czech Republic, August 2020; invited, but event corona-cancelled

**2019**

- Visualising Your Data Using R. Workshop for the Edinburgh CDCS. November 1, 2019
- Attractive, Interactive, Ready for the Web: Visualizing Your Data Using R. Workshop at the International Corpus Linguistics Conference 2019, Cardiff, Wales; July 2019
- Attractive, Interactive, Ready for the Web: Visualizing Your Data Using R. Workshop at the Digital Humanities 2019 conference, Utrecht, The Netherlands; July 2019
- Visualising Your Data Using R. Workshop at the SGSAH Summer School, Scotland; June 2019 
- Data exploration and visualisation using R, at the Scots Syntax Atlas Data Hack
- Jupyter Notebooks taster, SGSSS Summer School 2019; Scotland (co-teaching)
- Introduction to data exploration and visualization with R. Workshop at the PPLS LEL Spring Retreat to Firbush, Scotland; May 2019 
- Data visualization with R for corpus linguists, a workshop for "Corpus Linguistics in Scotland", 12 April 2019 
- Centre for Language Evolution PhD Retreat, Scotland; January 2019

**2018**

- University of Edinburgh PPLS Writing Centre summer quantitative workshops series 2018
- SGSSS Summer School, Scotland; 2018
- University of Edinburgh PPLS LEL Spring Retreat 2018
- University of Edinburgh PPLS Writing Centre short intro to R workshops, 2017-2018

**Other**

- Teaching in earlier years: R and stats teaching/tutoring at Edinburgh Uni Psychology 2017-2019; programming and NLP courses at the University of Tartu 2014-2016
- R workshop at the Academia Salensis summer school, Lithuania 2015.
- The short intro motivational "why-use-R" slides are [here](https://andreskarjus.github.io/artofthefigure/intro). And it's all open source: the entire Github repo is [here](https://github.com/andreskarjus/artofthefigure). 
